### ISSUE TITLE
New User Experience

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [ihdavids/orgextended_docs#1]
Hi,
First off, thanks for taking the time to implement this, I do appreciate the hard work. 
I came across the existence of OrgMode very recently and it looked like the next logical step as I'm constantly just making notes in Sublime. However, I have absolutely no experience with OrgMode or Emacs, and I instantly hit a wall when trying to use Orgextended. All I see is that I have many new org related syntaxes to try out
![image](https://user-images.githubusercontent.com/1378483/107672247-fa959a00-6c94-11eb-9a77-4fa896f1726a.png)
but again, I don't know what all these are for or how to use them.
I've tried to paste in the sample org file from and just do simple things like expand and collapse, but with no luck.

Is there any chance of some documentation for those in my position of having Sublime + Orgextended being their first foray into Orgmode?

**Comment by ihdavids** [comment]
Hi!

Yeah, my documentation is sadly lacking. I will work on it as time permits. (I started on some rework of the setup guide tonight!)
The only real syntax that matters from your prespective is OrgExtended. (Hence the camel case on it) The others are used in generated buffers.

There is a dizzying array of commands available for working in this mode, and I have not documented them even remotely well enough.

- First off: *.org files are orgmode files by default with this extension.
- * Heading gets you started with a heading.
- Tab is for collapsing and expanding. It is context aware. If you are on a heading it will cycle states for that heading. If you are on an unordered list it will collapse that. If you are on a src block it will collapse that.
- I have some keybindings that you can open up from the package menu. Not really good enough, I know... But documenting this thing is an ongoing process.
- I don't have a great guide to using OrgMode itself. There are a bunch of links in the ReadMe that talk about orgmode from a high level. Most of the basic features I support. I don't have support for column mode and although I have a very basic version of the babel execution engine in place, I don't have any of the neat chaining of data sources etc yet. That's on the todo list but it's not there yet. Part of the problem with writing a guide is that orgmode is super vast in what you can do with it. I do intend to write some content but it's not going to be super fast as I have limited time.

There is a lot you can do with org:
- Exporting
- Literate programming
- Capture mode
- Properties and Tags
- Todo lists, projects and tasks
- The agenda
- clocking and time tracking
- refiling
and all sorts of other things.

If you look here there are some pics of some of these things in action
https://orgmode.org/features.html

Perhaps I can help by asking you what you are interested in doing with org mode and see if I can help you along and target some of my documentation efforts to that area?

**Comment by Anti-Distinctlyminty** [comment]
The issue I was having was that I was hitting tab but nothing was happening. Well, nothing useful.
I discovered that the file needs to be saved for tab functions to work properly - just setting the syntax to OrgExtended wasn't enough. Quite often I wont save files to disk as Sublime keeps the files anyway, which I find really convenient, it would be great if it were possible to maintain this behaviour, but I can make a separate issue for that.

As for what I intended to use Org files for, the most pressing is a todo list. I'm currently using [Stickies](https://www.zhornsoftware.co.uk/stickies/download.html) and/or sublime text. I'm sure that org can do a vast amount of stuff, but I've only seen a few features which were enough to sell me on it, but my priority list for learning would be

- Todo lists, projects and tasks
- Changing state of todo list item
- Dates, calendar and scheduling
- The agenda

I think that if these are covered in a basic introductory manner it would be really helpful. I can see that there is an immense amount of functionality there, but at this stage I only need the basics, as it would already be a huge improvement over just using sublime for plain text todo lists.

Edit: I'm getting somewhere by looking at the keymap, so that's useful. But there the problem is knowing what to search for or what each item does, so a guide of some sort would still be useful, even if it just starts you down the super simple path of doing the items outlined above, then you just point people towards the keymap :)

Another Edit: I see that most commands are invoked with the alt+o, then more keys.  One thing that would be fantastic for discoverability is to have the status bar reflect options upon hitting alt+o.

**Comment by ihdavids** [comment]
Nice suggestions, 
I actually use neovintageous so the alt bindings are not something i use often myself.

I will see if I can work on an intro that walks you through basic note taking like that.
A lot of those things are "kind of" covered throughout the docs but a direct into could help new users.

I will see when I can make time.

**Comment by ihdavids** [comment]
I have started on a new user experience piece. I have a lot more to write, but what I have so far is here:
https://github.com/ihdavids/orgextended_docs/blob/master/learning_todos.org

**Comment by Anti-Distinctlyminty** [comment]
You work fast :)
Looking good so far. One suggestion I have is that it is essential is to know what the shortcut keys are to perform any given action. That was the biggest hurdle for me...I saw all this stuff happening in gifs and I didn't know how to make it happen.
(I've since gotten somewhere by looking through the keymap, but again because I've never used org before, I didn't know what I was looking for)

**Comment by Anti-Distinctlyminty** [comment]
For example, when discussing headings...

To make your first heading, use `* + space` then write the name of the heading.
To manipulate the headings, you can use
<table style="undefined;table-layout: fixed; width: 337px">
<colgroup>
<col style="width: 187px">
<col style="width: 150px">
</colgroup>
<thead>
  <tr>
    <td>Insert New Heading</th>
    <td>Ctrl + Enter</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>Insert Sub-Heading</td>
    <td>Ctrl + Shift + Enter</td>
  </tr>
  <tr>
    <td>Move Heading Up</td>
    <td>Alt+o, up</td>
  </tr>
  <tr>
    <td>Move Heading Down</td>
    <td>Alt+o, down</td>
  </tr>
  <tr>
    <td>Indent</td>
    <td>Alt+o, right</td>
  </tr>
  <tr>
    <td>Dedent</td>
    <td>Alt+o, left</td>
  </tr>
</tbody>
</table>

That kind of thing I find super useful. 
I'm actually happy to write some of this too, as it helps me learn (I usually write cheat sheets and stuff for myself anyway). I'm just not familiar enough with the org markup to do this very efficiently.

**Comment by ihdavids** [comment]
Yeah, I hear you.  I don't have a screen keys package to make those visible in the gif. The next best thing would be writing them down.

The key bindings would probably be best served by parsing them out of the keybindings file directly rather than manually writing them up in the docs. Perhaps I can write a little script for that. The commands should stay the same and I can just insert they keybindings in a table.

I am happy for you to help extend the docs, or the main package for that matter. Make a clone and push a PR! I am very open to collaborating.

**Comment by ihdavids** [comment]
I really should do that to add a reference of all the commands anyways!
There are a bunch of unbound commands that people might want to bind or use. Generating a table of that in the docs could really help.

**Comment by ihdavids** [comment]
Thanks for the PR. I appreciate the help!

**Comment by Anti-Distinctlyminty** [comment]
That's my first ever PR. Doing docs is somewhat less intimidating than getting into code :)
I'll slowly chip away at it as I'm learning. My plan is to go through the docs and list the default shortcut keys for each action shown, so new users can participate without having to open up and hunt through the keybindings.

**Comment by ihdavids** [comment]
:)

Good work, well done.

In the future, if I notice something in the PR I might comment on it, pushing changes to the branch will update the pr. In general, your command of english is probably better than mine, so most PRs will probably just be ingested immediately.

**Comment by ihdavids** [comment]
I added a reference page to the docs on keybindings. It's autogenerated from the commands and keybindings file so really not that much more than what you already had. Let me know if you see anything missing.

I think I have been through all the variants of active, recurring active, deadline, scheduled, recurrence, warnings without time, with time, with time range, for each of the time timestamp types now. I "THINK" they are functional. Boy there were quite a few annoying little gotchyas in there. 
Recurrences that get stuck, REALLY old scheduled tags that can bog down agenda creation, datetime conversion challenges and then switching from active to a closed state had to update and tag the item properly. (NOTE: deadlines et al that have a recurrence and are closed don't really close, they log the closure, update some properties and then update the base timestamp so they move through time. 

Let me know if you notice anything goofy with any of those. I am going to move on to other things for now.

**Comment by ihdavids** [comment]
1.1.6 should have the bulk of the updates including some performance improvements.
