### ISSUE TITLE
activating spacemacs keybindings

### ISSUE THREAD

**Issue by mikecuoco** [ihdavids/orgextended_docs#10]
Hi,

Thank you for this amazing package. I am coming from Spacemacs and hoping for a more user-friendly experience within sublime. I am trying to set up the package in Sublime 3 on macOS and cannot seem to get the spacemacs keybindings that you have in the keymap to work. The "alt+o" keys are working but I am hoping to move faster with the spacemacs bindings. Is there something I am missing to activate these bindings?

**Comment by ihdavids** [comment]
Those bindings are neovintageous aware.
IE: They require neovintageous be installed and active and most of them only work in normal mode vs insert mode.

One of the big let downs for me of late with ST4 (ST3 is still okay) is that NeoVintageous upgraded their runtime to the new python 3.8 runtime. (ST4 has 2 active runtimes, the old 3.3 and the newer 3.8 runtime) The problem there is I can no longer push directly into the neovintageous registers until I upgrade OrgExtended to 3.8. I have tried but 3.8 does not support package dependencies, which means I will have to pull the dependencies I am making use of directly into OrgExtended which has me a little frustrated. (or come up with a different solution, of which I have yet to do) I am told that the dependencies may not be supported for the 3.8 runtime, which has me somewhat worried.  

Regardless, be aware that if you choose to use ST4 (available from the ST discord channel) that "p" paste will not be able to paste things that OrgExtended has copied for you, like the create link feature that creates a link to the current heading on the clipboard for you etc.

**Comment by ihdavids** [comment]
NOTE: I cheat... I am not using the leader key as defined by your neovintageous setup, I am just assuming that your leader key is space... which may or may not frustrate some people. I figure they can just override my bindings to whatever they want if they don't like it. 

Hope this helps.

**Comment by ihdavids** [comment]
https://github.com/NeoVintageous/NeoVintageous
https://packagecontrol.io/packages/NeoVintageous

**Comment by mikecuoco** [comment]
Great! Thank you! I just installed and have the spacemacs keybindings working.

**Comment by ihdavids** [comment]
Great!
Glad you are up and running. I hope you find the package useful.
