### ISSUE TITLE
Checkbox summary not working

### ISSUE THREAD

**Issue by caobo** [ihdavids/orgextended_docs#4]
Love this plugin, it has much better user experience for note taking and task managing compare to markdown.
Thank you for bring orgmode to sublime text .

However, I have experienced a small issue, checkbox summary do not work in titles,
e.g. below is my todo list

* TODO [#A] someting [%]
    - [-] work-1 [2/3]
        - [x] a <2021-02-17 Wed>
        - [x] b <2021-02-17 Wed>
        - [ ] c
    - [ ] work-2 [0/1]
        - [ ] 2

* TODO [#A] someting [%] do not show the summarized information properly with "[%]" and "[/]" tag, how can I fix it?

**Comment by ihdavids** [comment]
I am glad you are finding some use from my plugin!

Yes, that is indeed something I do not currently support and probably should. The parser stops when it hits an org header.
I will see about adding that to my todo list.

I am going to move this item over to my OrgExtended repo. Sorry I have 2 repos, 1 for the docs and one for OrgExtended itself. That way the docs don't end up in my package and I can update them independent of the main package.

**Comment by ihdavids** [comment]
https://github.com/ihdavids/orgextended/issues
